export const itemOptions = [
  { key: "highPrice", label: "최고가격" },
  { key: "lowPrice", label: "최저가격" },
  { key: "str", label: "힘" },
  { key: "dex", label: "민첩" },
  { key: "int", label: "인트" },
  { key: "luk", label: "럭" },
  { key: "upgrade", label: "작횟수" },
  { key: "pad", label: "공격력" },
  { key: "mad", label: "마력" },
  { key: "hapma", label: "합마" },
  { key: "accuracy", label: "명중" },
  { key: "speed", label: "이속" },
  { key: "jump", label: "점프" },
  { key: "pdd", label: "물방" },
  { key: "mdd", label: "마방" },
  { key: "eva", label: "회피" },
  { key: "mhp", label: "HP" },
  { key: "mmp", label: "MP" },
];
